# Generated by Django 5.1.3 on 2025-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_invoiceitem_line_total_invoiceitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
