# Generated by Django 5.1.1 on 2025-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_invoiceitem_line_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='brand',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='part_number',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
