# Generated by Django 5.1.1 on 2025-05-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_customer_city_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
